# 3-D array


                    Collection of 2-D array / collection of matrix
                    

In [1]:
import numpy as np

In [2]:
arr_3d = np.array([
    [
        [23,45,56,56],
        [32,56,87,34]
    ],
    [
        [43,23,56,78],
        [43,56,23,56]
    ],
    [
        [11,23,12,34],
        [44,55,66,77]
    ]
])

In [3]:
arr_3d

array([[[23, 45, 56, 56],
        [32, 56, 87, 34]],

       [[43, 23, 56, 78],
        [43, 56, 23, 56]],

       [[11, 23, 12, 34],
        [44, 55, 66, 77]]])

In [4]:
arr_3d.ndim

3

In [5]:
arr_3d.shape

(3, 2, 4)

In [6]:
arr_3d.size

24

## indexing and slicing

        syntax:
        
                    indexing:
                                arr[record, row, col]
                                
                     slicing:
                     
                                arr[record_slicing, row_slicing, col_slicing]

In [7]:
arr_3d

array([[[23, 45, 56, 56],
        [32, 56, 87, 34]],

       [[43, 23, 56, 78],
        [43, 56, 23, 56]],

       [[11, 23, 12, 34],
        [44, 55, 66, 77]]])

In [8]:
arr_3d[0]

array([[23, 45, 56, 56],
       [32, 56, 87, 34]])

In [9]:
arr_3d[1, 0, 2]

56

In [10]:
arr_3d

array([[[23, 45, 56, 56],
        [32, 56, 87, 34]],

       [[43, 23, 56, 78],
        [43, 56, 23, 56]],

       [[11, 23, 12, 34],
        [44, 55, 66, 77]]])

In [11]:
arr_3d[::2]

array([[[23, 45, 56, 56],
        [32, 56, 87, 34]],

       [[11, 23, 12, 34],
        [44, 55, 66, 77]]])

In [12]:
arr_3d

array([[[23, 45, 56, 56],
        [32, 56, 87, 34]],

       [[43, 23, 56, 78],
        [43, 56, 23, 56]],

       [[11, 23, 12, 34],
        [44, 55, 66, 77]]])

In [13]:
arr = np.random.randint(125, 300, 200)
arr

array([295, 156, 150, 204, 167, 207, 127, 253, 237, 224, 130, 162, 248,
       218, 247, 204, 126, 126, 228, 200, 212, 203, 262, 198, 127, 262,
       262, 145, 235, 219, 271, 180, 214, 144, 250, 265, 169, 233, 138,
       272, 190, 251, 290, 140, 173, 201, 256, 229, 126, 148, 221, 214,
       256, 265, 298, 258, 175, 213, 165, 187, 231, 244, 269, 198, 209,
       226, 293, 246, 133, 176, 179, 184, 227, 187, 267, 139, 150, 254,
       261, 239, 271, 270, 240, 127, 148, 130, 135, 191, 240, 203, 130,
       276, 169, 181, 158, 147, 177, 138, 228, 129, 261, 226, 206, 190,
       172, 142, 189, 226, 238, 261, 167, 127, 190, 190, 255, 156, 270,
       220, 144, 198, 141, 270, 231, 235, 138, 235, 271, 255, 155, 154,
       299, 258, 272, 253, 190, 191, 254, 146, 164, 279, 290, 292, 214,
       189, 268, 212, 181, 161, 241, 144, 243, 207, 220, 232, 212, 212,
       185, 139, 250, 251, 265, 262, 271, 200, 205, 270, 268, 155, 292,
       262, 275, 228, 232, 223, 295, 186, 260, 225, 170, 158, 21

In [14]:
arr.reshape((25,2,4))

array([[[295, 156, 150, 204],
        [167, 207, 127, 253]],

       [[237, 224, 130, 162],
        [248, 218, 247, 204]],

       [[126, 126, 228, 200],
        [212, 203, 262, 198]],

       [[127, 262, 262, 145],
        [235, 219, 271, 180]],

       [[214, 144, 250, 265],
        [169, 233, 138, 272]],

       [[190, 251, 290, 140],
        [173, 201, 256, 229]],

       [[126, 148, 221, 214],
        [256, 265, 298, 258]],

       [[175, 213, 165, 187],
        [231, 244, 269, 198]],

       [[209, 226, 293, 246],
        [133, 176, 179, 184]],

       [[227, 187, 267, 139],
        [150, 254, 261, 239]],

       [[271, 270, 240, 127],
        [148, 130, 135, 191]],

       [[240, 203, 130, 276],
        [169, 181, 158, 147]],

       [[177, 138, 228, 129],
        [261, 226, 206, 190]],

       [[172, 142, 189, 226],
        [238, 261, 167, 127]],

       [[190, 190, 255, 156],
        [270, 220, 144, 198]],

       [[141, 270, 231, 235],
        [138, 235, 271, 255]],

       [

In [16]:
arr_3d = arr.reshape((10,5,4))
arr_3d

array([[[295, 156, 150, 204],
        [167, 207, 127, 253],
        [237, 224, 130, 162],
        [248, 218, 247, 204],
        [126, 126, 228, 200]],

       [[212, 203, 262, 198],
        [127, 262, 262, 145],
        [235, 219, 271, 180],
        [214, 144, 250, 265],
        [169, 233, 138, 272]],

       [[190, 251, 290, 140],
        [173, 201, 256, 229],
        [126, 148, 221, 214],
        [256, 265, 298, 258],
        [175, 213, 165, 187]],

       [[231, 244, 269, 198],
        [209, 226, 293, 246],
        [133, 176, 179, 184],
        [227, 187, 267, 139],
        [150, 254, 261, 239]],

       [[271, 270, 240, 127],
        [148, 130, 135, 191],
        [240, 203, 130, 276],
        [169, 181, 158, 147],
        [177, 138, 228, 129]],

       [[261, 226, 206, 190],
        [172, 142, 189, 226],
        [238, 261, 167, 127],
        [190, 190, 255, 156],
        [270, 220, 144, 198]],

       [[141, 270, 231, 235],
        [138, 235, 271, 255],
        [155, 154, 299, 258]

In [17]:
arr_3d[1::3, ::-1, ::-1]

array([[[272, 138, 233, 169],
        [265, 250, 144, 214],
        [180, 271, 219, 235],
        [145, 262, 262, 127],
        [198, 262, 203, 212]],

       [[129, 228, 138, 177],
        [147, 158, 181, 169],
        [276, 130, 203, 240],
        [191, 135, 130, 148],
        [127, 240, 270, 271]],

       [[251, 250, 139, 185],
        [212, 212, 232, 220],
        [207, 243, 144, 241],
        [161, 181, 212, 268],
        [189, 214, 292, 290]]])

In [18]:
arr_2d = np.arange(1, 51).reshape((10,5))
arr_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [20]:
ls = []

for i in list(arr_2d):
    ls.extend(i)

In [22]:
print(ls)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]


## matrix multiplication

In [23]:
a = np.random.randint(120, 150, 20).reshape((5,4))
b = np.random.randint(10, 30, 20).reshape((5,4))

In [24]:
a

array([[126, 131, 132, 129],
       [140, 130, 125, 137],
       [140, 129, 122, 122],
       [133, 146, 145, 143],
       [132, 136, 123, 126]])

In [25]:
b

array([[14, 21, 14, 21],
       [12, 20, 11, 13],
       [13, 10, 19, 27],
       [22, 17, 28, 26],
       [13, 14, 15, 20]])

In [26]:
a / b

array([[ 9.        ,  6.23809524,  9.42857143,  6.14285714],
       [11.66666667,  6.5       , 11.36363636, 10.53846154],
       [10.76923077, 12.9       ,  6.42105263,  4.51851852],
       [ 6.04545455,  8.58823529,  5.17857143,  5.5       ],
       [10.15384615,  9.71428571,  8.2       ,  6.3       ]])

In [28]:
a * b          # element wise multiplication

array([[1764, 2751, 1848, 2709],
       [1680, 2600, 1375, 1781],
       [1820, 1290, 2318, 3294],
       [2926, 2482, 4060, 3718],
       [1716, 1904, 1845, 2520]])

In [29]:
A = np.array([
    [1,2],
    [3,4],
    [5,6]
])

B = np.array([
    [10, 12, 13, 14],
    [1, 2, 3, 4]
])

In [30]:
A


array([[1, 2],
       [3, 4],
       [5, 6]])

In [31]:
B

array([[10, 12, 13, 14],
       [ 1,  2,  3,  4]])

In [32]:
A * B

ValueError: operands could not be broadcast together with shapes (3,2) (2,4) 

In [33]:
A @ B

array([[12, 16, 19, 22],
       [34, 44, 51, 58],
       [56, 72, 83, 94]])

In [34]:
np.matmul(A,B)

array([[12, 16, 19, 22],
       [34, 44, 51, 58],
       [56, 72, 83, 94]])

In [35]:
np.dot(A,B)

array([[12, 16, 19, 22],
       [34, 44, 51, 58],
       [56, 72, 83, 94]])

    np.arange
    np.random.randint
    np.eye
    np.full
    np.empty
    np.linspace
    np.random.normal
    np.random.uniform
    np.random.binomial
    np.once
    np.zeros

In [36]:
np.arange(10, 101, 10)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [37]:
np.arange(-5, 5)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [38]:
np.arange(10, 21, .5)

array([10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. ,
       15.5, 16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5])

In [39]:
np.random.randint(100, 501, 100)

array([402, 444, 420, 191, 151, 298, 285, 423, 386, 304, 308, 231, 325,
       462, 114, 379, 207, 359, 378, 121, 219, 173, 385, 287, 438, 275,
       250, 384, 193, 212, 245, 311, 183, 187, 500, 165, 362, 201, 396,
       316, 273, 378, 207, 496, 323, 182, 359, 362, 165, 327, 142, 100,
       438, 394, 175, 232, 433, 314, 197, 457, 481, 456, 296, 348, 252,
       456, 362, 358, 320, 404, 375, 291, 389, 251, 494, 131, 353, 430,
       382, 478, 375, 215, 260, 382, 255, 380, 192, 308, 180, 353, 157,
       145, 447, 294, 427, 218, 273, 228, 377, 278])

In [40]:
np.linspace(10, 20)

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [41]:
np.linspace(10, 20, 100)

array([10.        , 10.1010101 , 10.2020202 , 10.3030303 , 10.4040404 ,
       10.50505051, 10.60606061, 10.70707071, 10.80808081, 10.90909091,
       11.01010101, 11.11111111, 11.21212121, 11.31313131, 11.41414141,
       11.51515152, 11.61616162, 11.71717172, 11.81818182, 11.91919192,
       12.02020202, 12.12121212, 12.22222222, 12.32323232, 12.42424242,
       12.52525253, 12.62626263, 12.72727273, 12.82828283, 12.92929293,
       13.03030303, 13.13131313, 13.23232323, 13.33333333, 13.43434343,
       13.53535354, 13.63636364, 13.73737374, 13.83838384, 13.93939394,
       14.04040404, 14.14141414, 14.24242424, 14.34343434, 14.44444444,
       14.54545455, 14.64646465, 14.74747475, 14.84848485, 14.94949495,
       15.05050505, 15.15151515, 15.25252525, 15.35353535, 15.45454545,
       15.55555556, 15.65656566, 15.75757576, 15.85858586, 15.95959596,
       16.06060606, 16.16161616, 16.26262626, 16.36363636, 16.46464646,
       16.56565657, 16.66666667, 16.76767677, 16.86868687, 16.96

In [42]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [44]:
arr = np.zeros((5,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [45]:
arr += 10

In [46]:
arr

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

In [49]:
np.zeros((5,3,4), dtype='int')

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [50]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [51]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [52]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [54]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [56]:
np.eye(5, 5, -1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [57]:
np.eye(5, 5, 1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [59]:
empty = np.empty((5,6))
empty

array([[1.21182596e-311, 1.02765654e-321, 0.00000000e+000,
        0.00000000e+000, 8.01097888e-307, 5.02034658e+175],
       [1.32597988e-075, 4.79122068e-037, 1.86420042e+160,
        3.73253024e-033, 4.22287328e-062, 8.07741486e-144],
       [3.59751658e+252, 3.96046095e+246, 1.04918621e-153,
        7.69165785e+218, 5.04621343e+180, 1.04917822e-153],
       [9.08366793e+223, 1.32597988e-075, 4.79122068e-037,
        1.86420042e+160, 3.73253024e-033, 1.04915031e-153],
       [1.94918966e-153, 2.57707751e-057, 2.26199900e-076,
        4.18486813e-062, 2.59027896e-144, 7.79952704e-143]])

In [61]:
empty

array([[1.21182596e-311, 1.02765654e-321, 0.00000000e+000,
        0.00000000e+000, 8.01097888e-307, 5.02034658e+175],
       [1.32597988e-075, 4.79122068e-037, 1.86420042e+160,
        3.73253024e-033, 4.22287328e-062, 8.07741486e-144],
       [3.59751658e+252, 3.96046095e+246, 1.04918621e-153,
        7.69165785e+218, 5.04621343e+180, 1.04917822e-153],
       [9.08366793e+223, 1.32597988e-075, 4.79122068e-037,
        1.86420042e+160, 3.73253024e-033, 1.04915031e-153],
       [1.94918966e-153, 2.57707751e-057, 2.26199900e-076,
        4.18486813e-062, 2.59027896e-144, 7.79952704e-143]])

In [62]:
empty += 5

In [63]:
empty

array([[5.00000000e+000, 5.00000000e+000, 5.00000000e+000,
        5.00000000e+000, 5.00000000e+000, 5.02034658e+175],
       [5.00000000e+000, 5.00000000e+000, 1.86420042e+160,
        5.00000000e+000, 5.00000000e+000, 5.00000000e+000],
       [3.59751658e+252, 3.96046095e+246, 5.00000000e+000,
        7.69165785e+218, 5.04621343e+180, 5.00000000e+000],
       [9.08366793e+223, 5.00000000e+000, 5.00000000e+000,
        1.86420042e+160, 5.00000000e+000, 5.00000000e+000],
       [5.00000000e+000, 5.00000000e+000, 5.00000000e+000,
        5.00000000e+000, 5.00000000e+000, 5.00000000e+000]])

In [64]:
empty.sum()

3.597520545210126e+252

In [65]:
np.inf

inf

In [66]:
np.pi

3.141592653589793

In [67]:
np.full((3,4), np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [68]:
np.full((5,6), np.inf)

array([[inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf]])

In [69]:
arr

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

In [70]:
arr = np.arange(1, 21).reshape((4,5))

In [71]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [72]:
arr.T

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

In [73]:
np.transpose(arr)

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

In [74]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [77]:
for i in zip(*arr):
    print(i)

(1, 6, 11, 16)
(2, 7, 12, 17)
(3, 8, 13, 18)
(4, 9, 14, 19)
(5, 10, 15, 20)


In [79]:
np.array(list(zip(*arr)))

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

In [80]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [81]:
for i in zip(*arr):
    print(i)

(1, 6, 11, 16)
(2, 7, 12, 17)
(3, 8, 13, 18)
(4, 9, 14, 19)
(5, 10, 15, 20)
